### PR TITLE
Update anomaly_detection model for new photometry

### PR DESCRIPTION
**Pull request by matwey**
**IMPORTANT: Please create an issue first before opening a Pull Request.**
Linked to issue(s): Closes _put link_

## What changes were proposed in this pull request?

Retrain anomaly_detection model on ` lc_features_20210617_photometry_corrected.parquet`

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Hi @matwey -- thanks for the retraining. Any ideas why the model grew from 13MB to 30MB with a similar dataset?

**Comment by matwey** [comment]
Hi @JulienPeloton 

1. I've retrained using `sklearn 1.0.2` and Python 3.9 and force-pushed the commit
2. Currently, I use notebooks provided by @VoidDruid and there is a hyper-parameter tuning stage with `GridSearchCV`. I suppose that hyper-parameters (trees number) appeared to be different for different data.

However, I think that it is desirable to migrate to ONNX to address both questions. First, it is size-efficient, second it is version compatible. I think this should be next step for this module.

**Comment by JulienPeloton** [comment]
Thanks for the retraining -- there is one unit test failing (expected as you changed the model):

```
File "/__w/fink-science/fink-science/fink_science/__init__.py", line ?, in __main__.anomaly_score
Failed example:
    df.filter(df["anomaly_score"] < -0.5).count()
Expected:
    15
Got:
    7
```

> However, I think that it is desirable to migrate to ONNX to address both questions

I completely agree!

**Comment by matwey** [comment]
> Thanks for the retraining -- there is one unit test failing (expected as you changed the model):
> 
> ```
> File "/__w/fink-science/fink-science/fink_science/__init__.py", line ?, in __main__.anomaly_score
> Failed example:
>     df.filter(df["anomaly_score"] < -0.5).count()
> Expected:
>     15
> Got:
>     7
> ```

This was from a docsting, and fixed now.

**Comment by JulienPeloton** [comment]
Thanks! I'm merging.

**Pull request merged**
