### PR TITLE
Fix SNN & active learning elasticc modules

### PR DESCRIPTION
**Pull request by JulienPeloton**
**IMPORTANT: Please create an issue first before opening a Pull Request.**
Linked to issue(s): #286 #284

## If this is a new release, did you issue the corresponding schema in fink-client?

N/A

## What changes were proposed in this pull request?

Fix the failures for SNN elasticc & Active Learning elasticc.

## How was this patch tested?

CI

### CODE REVIEW

**Comment by JulienPeloton** [comment]
@marcol480 -- I take over the development. I change a bit the syntax, but if I understand correctly, the new version concatenates the lightcurve features and the meta features? So if I have N features, and M meta features, the vector for inference should have a length of N+M?

Because currently, I have features which is of size 36 (6 bands, and 6 features per band) + meta features which is always 5 features --> 41 features, and the code is screaming at me with:

```
ValueError: X has 41 features, but RandomForestClassifier is expecting 43 features as input
```
Do we miss meta features? We currently have:

```
hostgal_ra, hostgal_dec, hostgal_zphot, hostgal_zphot_err, mwebv
```

**Comment by JulienPeloton** [comment]
@marcol480 -- I have the impression that you also need `ra` and `dec` (and not just `hostgal_ra`, `hostag_dec`)

**Comment by marcol480** [comment]
Salut Julien, yes that is correct, there is a number of fixed meta features , regardless of the bands. 

The first model I pushed had also ‘ra’ and ‘dec’, whereas after discussing with you I understood ra and dec are just random here. I thought I had uploaded the model with no ra and dec but apparently that is not the case...
I will need to change this in a second moment. I will re-open an issue.
Thanks!

**Comment by JulienPeloton** [comment]
Thanks! If you can, just send me the model via Slack, I will push it :-)

**Comment by JulienPeloton** [comment]
But wait -- if you have both `ra, dec` and `hostgal_ra, hostgal_dec`, then it may makes sense (because the classifier will learn object close to galaxy -- irrespective on where they are on the sky). How where the performances with/without `ra,dec`? Did you see a big change?

**Comment by marcol480** [comment]
Ah, I did not really check without ra, dec. I have to look at the metrics
Marco

**Comment by JulienPeloton** [comment]
Do not worry -- let's keep as it (ra, dec, hostgal_ra, hostgal_dec), and look at the rest after holidays. The model now passes, and at least we will have a first look at the results.

**Comment by marcol480** [comment]
OK, yes let's have a look at these results first!

**Pull request merged**
