### PR TITLE
subset Y1 elasticc train

### PR DESCRIPTION
**Pull request by anaismoller**
## What changes were proposed in this pull request?

Only new models to be tested

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Could you pull latest change from `master` branch? I just shipped a bug fix.

**Comment by JulienPeloton** [comment]
Thanks -- one more thing before the merge: as you uploaded a new model, the current test suite is failing (because your predictions are different). Could you check the new test results make sense? For reference, the test data set I use is at:

```
fink_science/data/alerts/elasticc_sample_seed0.parquet
```

**Comment by anaismoller** [comment]
Thanks! we should use a s a test the training.log to see the accuracy is above a threshold instead of looking directly of probabilities. What do you think?

**Comment by JulienPeloton** [comment]
Yes, this is a good idea, I can add this! 
But I would still look at probabilities as well as it is also a way to check the pipeline is working (from the technical pov) and how two models differ (the exact number is not interesting -- but if one model is classifying 10 times more objects, that's usually a sign that something is fishy).

**Pull request merged**
