### PR TITLE
[Elasticc] updated CATS model from paper review

### PR DESCRIPTION
**Pull request by and-santos**
PR with updated cat model as described in #432

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Thanks @and-santos -- can you also update the default model to use?
https://github.com/astrolabsoftware/fink-science/blob/08344210536246ee57e69f7c14d27a03fa6f2033/fink_science/cats/processor.py#L185

**Comment by JulienPeloton** [comment]
Hello @and-santos -- I do not understand why you pushed two models (`.h5` and `.keras`)? Moreover, the CI is failing with a cryptic error: `OSError: Unable to synchronously open file (file signature not found)`. Do you have any ideas?

https://github.com/astrolabsoftware/fink-science/actions/runs/11131240753/job/30932370237?pr=433

**Comment by JulienPeloton** [comment]
With the new version of tensorflow, the model loads correctly :tada: 

But the CI fails because of the import of `tensorflow_addons`. I will remove it from the container, but can you remove the line 26 in `processor.py`

```
from tensorflow_addons import optimizers
```

Thanks!

**Comment by and-santos** [comment]
> With the new version of tensorflow, the model loads correctly 🎉
> 
> But the CI fails because of the import of `tensorflow_addons`. I will remove it from the container, but can you remove the line 26 in `processor.py`
> 
> ```python
> from tensorflow_addons import optimizers
> ```
> 
> Thanks!

Thanks for pointing that out. I removed the import  :+1:

**Comment by JulienPeloton** [comment]
The CI now fails with the pickle error:

```
Traceback (most recent call last):
  File "/home/libs/spark-3.4.1-bin-hadoop3/python/pyspark/serializers.py", line 459, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
  File "/home/libs/spark-3.4.1-bin-hadoop3/python/pyspark/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/libs/spark-3.4.1-bin-hadoop3/python/pyspark/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'KerasLazyLoader' object
```

on which versions of Spark did you test at CBPF?

**Comment by and-santos** [comment]
> The CI now fails with the pickle error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/libs/spark-3.4.1-bin-hadoop3/python/pyspark/serializers.py", line 459, in dumps
>     return cloudpickle.dumps(obj, pickle_protocol)
>   File "/home/libs/spark-3.4.1-bin-hadoop3/python/pyspark/cloudpickle/cloudpickle_fast.py", line 73, in dumps
>     cp.dump(obj)
>   File "/home/libs/spark-3.4.1-bin-hadoop3/python/pyspark/cloudpickle/cloudpickle_fast.py", line 632, in dump
>     return Pickler.dump(self, obj)
> TypeError: cannot pickle 'KerasLazyLoader' object
> ```
> 
> on which versions of Spark did you test at CBPF?

I am using pyspark==3.5.3. My Full dependecies are:

```
name: fink-dev
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.46.1=hadc24fc_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=pyh8b19718_1
  - python=3.9.20=h13acc7a_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=hc8b5060_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.1.0
      - anyio==4.6.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - debugpy==1.8.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - flatbuffers==24.3.25
      - fqdn==1.5.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.2
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.10
      - importlib-metadata==8.5.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==3.6.0
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.13.0
      - overrides==7.7.0
      - packaging==24.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - protobuf==4.25.5
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py4j==0.10.9.7
      - pycparser==2.22
      - pygments==2.18.0
      - pyspark==3.5.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.2
      - rpds-py==0.20.0
      - send2trash==1.8.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - tinycss2==1.3.0
      - tomli==2.0.2
      - tornado==6.4.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - zipp==3.20.2
prefix: /home/delta/andsantos/miniforge3/envs/fink-dev
```

**Comment by JulienPeloton** [comment]
Wait -- you have tensorflow 2.17 and keras 3.6 ? I will make test using the Fink docker image tomorrow -- but when you are training, it is better if you can stick with the same dependencies than the ones we are using in Fink.

**Comment by JulienPeloton** [comment]
Actually the offending line is 

```python
from tensorflow import keras
```

it cannot be declared in the global namespace -- and it should be put inside the pandas UDF:

```python
def predict_nn(...)
    """ doc """
    from tensorflow import keras # <--- put it here
    filter_dict = {'u': 1, 'g': 2, 'r': 3, 'i': 4, 'z': 5, 'Y': 6}
    ...
```

Then as the model changed, you must change the results of the test:

```diff
>>> df.filter(df['argmax'] == 0).count()
- 55
+ 65
```

**Comment by and-santos** [comment]
> Actually the offending line is
> 
> ```python
> from tensorflow import keras
> ```
> 
> it cannot be declared in the global namespace -- and it should be put inside the pandas UDF:
> 
> ```python
> def predict_nn(...)
>     """ doc """
>     from tensorflow import keras # <--- put it here
>     filter_dict = {'u': 1, 'g': 2, 'r': 3, 'i': 4, 'z': 5, 'Y': 6}
>     ...
> ```
> 
> Then as the model changed, you must change the results of the test:
> 
> ```diff
> >>> df.filter(df['argmax'] == 0).count()
> - 55
> + 65
> ```



> Actually the offending line is
> 
> ```python
> from tensorflow import keras
> ```
> 
> it cannot be declared in the global namespace -- and it should be put inside the pandas UDF:
> 
> ```python
> def predict_nn(...)
>     """ doc """
>     from tensorflow import keras # <--- put it here
>     filter_dict = {'u': 1, 'g': 2, 'r': 3, 'i': 4, 'z': 5, 'Y': 6}
>     ...
> ```
> 
> Then as the model changed, you must change the results of the test:
> 
> ```diff
> >>> df.filter(df['argmax'] == 0).count()
> - 55
> + 65
> ```

I put both tensorflow imports inside the pandas UDF. Sorry for the "pep8 changes", I was using an editor without python linting

**Comment by JulienPeloton** [comment]
Thanks, it is all green now!

**Pull request merged**
